### ISSUE TITLE
Thermostat card not rendering correctly in Column card

### ISSUE THREAD

**Issue by gadgetchnnel** [thomasloven/lovelace-column-card#2]
When adding the new Thermostat card as a card within the Column card, it does not render correctly.

Example Config:

    - type: custom:column-card
      cards:
        - type: thermostat
          entity: climate.bedroom

It renders like this:

<img width="559" alt="screen shot 2018-11-03 at 11 16 08" src="https://user-images.githubusercontent.com/2099542/47953477-15391e80-df76-11e8-8dd3-25fd1b14424e.png">

**Comment by thomasloven** [comment]
This is fixed in layout-card: https://github.com/thomasloven/lovelace-layout-card which replaces column-card and is better in every way.
